### ISSUE TITLE
Issues accessing files when sharing as "website"

### ISSUE THREAD

**Issue by n8fr8** [onionshare/onionshare-ios#1]
Added some files to share in "Share" view and "Website" view, but couldn't access the files when shared as website.

See the video!

https://user-images.githubusercontent.com/30851/157895057-7648c3c5-f8a7-472d-91f1-fd86165fee10.mov

**Comment by tladesignz** [comment]
Sorry, I can't reproduce this. Tried with a simulator and a real device, to no avail.

Some network hickup?

**Comment by tladesignz** [comment]
Closed due to inactivity.
