### ISSUE TITLE
Sheet UI - Ready State

### ISSUE THREAD

**Issue by glenn-sorrentino** [onionshare/onionshare-ios#10]
**Current**
-Sheet heading needs greater hierarchy.
-Share button gets lost in the UI.
-Start Sharing button is the primary action, but the button's footprint doesn't reflect its priority.
-The box-shadow is pretty strong.
-The styles appear as:
`sheet { box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.9); } h1 { font-size: 17pt; } button { width: fit-content; }`

**Expected**
-Add padding and background color to sharing buttons to add emphasis.
-Make primary button full-width of the sheet.
-Uniform alignment of UI elements.
-Styles adjusted to:
`sheet { box-shadow: 0px 0px 24px rgba(0, 0, 0, 0.14); } h1 { font-size: 22pt; font-weight: bold; } button { width: 100%; font-weight: normal; }`

![sheet-ready-state](https://user-images.githubusercontent.com/28545431/159778415-3655f835-9c37-481d-95e8-1d6368bda424.png)

**Comment by tladesignz** [comment]
Fixed with https://github.com/tladesignz/AdParticipesCumCepis/commit/90fc1cf4562d5036b878297ad8a72cd21ad6b2bc
