### ISSUE TITLE
Tab Labels

### ISSUE THREAD

**Issue by glenn-sorrentino** [onionshare/onionshare-ios#12]
**Current**
Tab labels use different conventions for naming - one is a verb, the other a noun

**Expected**
Use verbs for both tabs.

![tab-labels](https://user-images.githubusercontent.com/28545431/159785992-f72d104c-09d9-425e-bf8b-e1e529ff24ee.png)

**Comment by tladesignz** [comment]
I did take this from the original OnionShare desktop app. That's the exact tab labels used there.

I'm totally with you, that "Share" and "Host" feels better than "Share" and "Website", so I will do the change, but be informed, that we're then becoming inconsistent with the original. Maybe it should be changed there, too?

**Comment by tladesignz** [comment]
Ahaha! Also be informed, that in other languages this might actually not work.
E.g. in German there's no good translation for "to host". A host is a "Gastgeber". To host translates to "Gastgeber sein" (literally "to be a host"). That's not only way too long but also completely misses the point. In German one can only be a "Gastgeber" to other persons at e.g. a dinner party. Not being a "Gastgeber" for Websites.

In German you would express this like this: "Einen Webserver laufen lassen". Literally: "to have a webserver running". So, there's a foreign word involved and it's also very long. In the end, I have to actually translate "Host" (the verb) to "Website" to make sense of this in German and be usable as a short word on a tab and heading...
