### ISSUE TITLE
Progress Indicator Styling

### ISSUE THREAD

**Issue by glenn-sorrentino** [onionshare/onionshare-ios#13]
**Current**
The progress indicator is a percent-based number.

**Expected**
A progress bar to provide visual feedback.

![Frame 133](https://user-images.githubusercontent.com/28545431/161170085-c6752400-af77-4284-9cd8-a6a912a3a446.png)

**Comment by tladesignz** [comment]
Fixed with 5b5c8d3e76cc1ac3b901c9f019e45192a24890da.
