### ISSUE TITLE
Unable to Download Videos

### ISSUE THREAD

**Issue by ingfabby** [onionshare/onionshare-ios#15]
Device: iPhone XR, iOS 15.3.1
Onion Share Version: 0.1.0 (7)

Steps followed:
1.-I opened the app
2.-Went to the "Share" section
3.-Selected a video to share
4.-Copied the link when it was ready
5.-Open the link on Tor Browser for Android
6.-Tap on "Download Files"
7.-The video opened on the browser but did not download.
*I was able to download images and folders with images and videos in them, but not single videos.

**Comment by tladesignz** [comment]
Good catch, @ingfabby, thank you!

Single files should also be sent as "attachment", like mulitple zipped-up files are.

**Comment by tladesignz** [comment]
Fixed with https://github.com/tladesignz/AdParticipesCumCepis/commit/2e97be0494840fb101bdea353b2e7108593c63b7
