### ISSUE TITLE
Sheet UI - excessive margin under button

### ISSUE THREAD

**Issue by glenn-sorrentino** [onionshare/onionshare-ios#16]
**Current**
The margin under the primary button adds excessive negative space to the UI.

**Expected**
Margin should be ~1rem/16px. 

![sheet-ui](https://user-images.githubusercontent.com/28545431/163653641-15869ea5-8a09-4e25-996f-81be65bd5583.png)

**Comment by tladesignz** [comment]
Oh my, you caused me a lot of headaches. But it's done:
https://github.com/tladesignz/AdParticipesCumCepis/commit/6fb4202878323c248b02735dfb2b6177e93ec0a1

I'm still not falling in love with SwiftUI.
