### ISSUE TITLE
Sheet UX - button functionality

### ISSUE THREAD

**Issue by glenn-sorrentino** [onionshare/onionshare-ios#17]
**Current**
There's no way to cancel the startup process.

**Expected**
Improve error-recovery UX by adding the ability to cancel at any time.

![sheet-ux](https://user-images.githubusercontent.com/28545431/163653702-61f72f9f-d75a-4867-954e-ef5a7d163b0f.png)

**Comment by tladesignz** [comment]
That's on purpose. I'd prefer it to work, but I can't make it stably do so. Stopping Tor mid-startup will make subsequent startups unreliable, due to running in-process which Tor was never designed for.
