### ISSUE TITLE
File List UX - Add Folder Drill-In

### ISSUE THREAD

**Issue by glenn-sorrentino** [onionshare/onionshare-ios#20]
**Current**
User cannot drill in to a folder.

**Expected**
- Allow drill-in, even if there are no contents within the folder.
- Displaying a chevron.right icon to indicate functionality.

![file-list-ux](https://user-images.githubusercontent.com/28545431/163656360-9632438e-c778-4371-8e69-63e42b1f467b.png)

**Comment by tladesignz** [comment]
You seriously want me to rebuild a file picker functionality? I think I left it at that, because OS Desktop works the same.

How do you suggest to implement navigation? How to indicate the current level?

**Comment by glenn-sorrentino** [comment]
Well, not suggesting the solution, just pointing out a gap in the standard interaction pattern for navigating files on iOS. We can shelve this for now since it seems like a lot of work, but I think we should consider it in the future.
