### ISSUE TITLE
add webhook for weblate

### ISSUE THREAD

**Issue by n8fr8** [onionshare/onionshare-ios#25]
Weblate is prepared to receive information when a repository has been updated, with a notification webhook.
This will prevent the problems with merges etc.

The webhook URL is simply https://hosted.weblate.org/hooks/github/

Here the instructions: https://docs.weblate.org/en/weblate-4.14.1/admin/continuous.html#github-setup

There is also a Weblate app for github but I have no idea what that is. The webhook works very well to prevent merge conflicts!

**Comment by tladesignz** [comment]
Unfortunately, I don't have enough permissions to add a web hook.

@micahflee, can you take care of this?

Thank you!

**Comment by micahflee** [comment]
I just added the webhook for weblate! Let me know if there are any issues with it.
![image](https://user-images.githubusercontent.com/156128/195375033-cb92bd97-21b5-418e-99dd-c587be868040.png)
