### ISSUE TITLE
Reduce Margin Above Half Sheet Toggles

### ISSUE THREAD

**Issue by glenn-sorrentino** [onionshare/onionshare-ios#28]
Current UI: Excessive margin above half-sheet toggles.

Expected UI: Reduced to 25% its original height, from 88px, to 22px.

![Slice 1](https://user-images.githubusercontent.com/28545431/197280597-974ae294-1009-4e0d-96f0-70ca771405a7.png)

**Comment by tladesignz** [comment]
Improved with https://github.com/tladesignz/AdParticipesCumCepis/commit/7743388c8ff226ffcc6339d44bdaae90b7d24e01

Unfortunately, SwiftUI is not pixel-perfect. There's a padding which seems to be introduced automatically, and I have no idea where that comes from.

I could remove the padding somewhat, though.

**Comment by tladesignz** [comment]
Please review in upcoming TestFlight build 15.

**Comment by tladesignz** [comment]
Since no feedback for 3 months, I assume ok.
