### ISSUE TITLE
Update disabled button color while OnionShare is starting

### ISSUE THREAD

**Issue by glenn-sorrentino** [onionshare/onionshare-ios#29]
Current UI: After the user taps "Start Sharing" the button changes to a dark grey color of #545454.

Expected UI: The default color should be changed to 50% opacity to communicate the disabled state.

![Slice 2](https://user-images.githubusercontent.com/28545431/197281417-0524a5a0-4aca-46df-bacf-056987f438ba.png)

**Comment by tladesignz** [comment]
Fixed in https://github.com/tladesignz/AdParticipesCumCepis/commit/e69384531f691f0dab2e2e0aeba7d6780138eb40

Please review in upcoming TestFlight build 15.

**Comment by tladesignz** [comment]
Since no feedback for 3 months, I assume ok.
