### ISSUE TITLE
Update background color

### ISSUE THREAD

**Issue by glenn-sorrentino** [onionshare/onionshare-ios#30]
Current UI: After the user selects files to share, the background becomes grey, creating issues with grouping, contrast, and consistency. 

Expected UI: all backgrounds are white.

![Slice 3](https://user-images.githubusercontent.com/28545431/197281928-1e742f1f-479f-426e-bc87-56ac3fcc0824.png)

**Comment by tladesignz** [comment]
Since no feedback for 3 months, I assume ok.
