### ISSUE TITLE
Reduce Half-Sheet Drop Shadow

### ISSUE THREAD

**Issue by glenn-sorrentino** [onionshare/onionshare-ios#31]
Current UI: The drop shadow is a little heavy, maybe #000 ~25%?

Expected: The shadow should be lighter, around 15%, and if possible an outline (outer border) of rgba(0,0,0,0.15) for better edge contrast.

![Slice 4](https://user-images.githubusercontent.com/28545431/197283152-1b6de025-b98f-4f0f-9685-51c229c9f437.png)

**Comment by tladesignz** [comment]
Since no feedback for 3 months, I assume ok.
