### ISSUE TITLE
Remove Host Functionality 

### ISSUE THREAD

**Issue by glenn-sorrentino** [onionshare/onionshare-ios#32]
Current Functionality: Both Host and Share functions are present. iOS is unique in this featureset.

Expected: 
- Only Share functionality
- Heading should be updated to display name of app

![Slice 5](https://user-images.githubusercontent.com/28545431/197284831-bc556a2e-ac86-471f-ab4a-1a8b56ce3bbd.png)

**Comment by tladesignz** [comment]
Please review in upcoming TestFlight build 15.

**Comment by tladesignz** [comment]
Since no feedback for 3 months, I assume ok.
