### ISSUE TITLE
More Prominent Progress Bar

### ISSUE THREAD

**Issue by glenn-sorrentino** [onionshare/onionshare-ios#33]
Current UI: Progress bar looks like it's ~3px.

Expected: 2x the original width.

![Slice 6](https://user-images.githubusercontent.com/28545431/197285538-d1e6ba0e-d84b-4c7e-b2e3-b101a4c63adc.png)

**Comment by tladesignz** [comment]
Fixed here:
https://github.com/tladesignz/AdParticipesCumCepis/commit/d9bc353fd4f2c2524f49d3e6950d80b8c781ce5b

Please review in upcoming TestFlight build 15.

**Comment by tladesignz** [comment]
Since no feedback for 3 months, I assume ok.
