### ISSUE TITLE
Prepare release

### ISSUE THREAD

**Issue by tladesignz** [onionshare/onionshare-ios#36]
To finally get this out the door, we're going to need the following:

- [x] Somebody with permission to fill the App Store details (Micah?)
- [x] Decision which which version number we start? 0.1.0? 1.0.0? Something else?
- [x] All necessary App Store metadata in (at least) English.

I'll commit empty Fastlane metadata files, so we have a better idea what we need and where we can work collaboratively on.
You will find them here: https://github.com/onionshare/onionshare-ios/tree/main/fastlane

Here is some description of the files and potential values: https://docs.fastlane.tools/actions/deliver/#tips

Here screenshots of App Store Connect so you can see where it's going to go:

![Screenshot 2023-01-10 at 16-18-24 App Store Connect](https://user-images.githubusercontent.com/117089/211592386-ffa22724-227f-48d3-8605-742b700b2588.png)

![Screenshot 2023-01-10 at 16-19-04 App Store Connect](https://user-images.githubusercontent.com/117089/211592417-3f8a075f-a646-4ac9-b5ff-cf9a7bc0bdeb.png)

![Screenshot 2023-01-10 at 16-19-19 App Store Connect](https://user-images.githubusercontent.com/117089/211592431-7f363f5a-f74c-4b6a-b617-05108afa4ae8.png)

**Comment by tladesignz** [comment]
@n8fr8: Cannot assign you...

**Comment by tladesignz** [comment]
For reference, here's the metadata of Orbot Apple: https://github.com/guardianproject/orbot-apple/tree/main/fastlane/metadata

**Comment by tladesignz** [comment]
Just texted with Micah: We'll start with version 1.0.0.

**Comment by micahflee** [comment]
@tladesignz I think you should have the permissions necessary to make releases in App Store Connect. Let me know if you don't.

**Comment by tladesignz** [comment]
@micahflee, great, thank you! Ok, so we now "just" need all the texts. @n8fr8, where are we on that front?

**Comment by tladesignz** [comment]
- [ ] need additional "screenshots"/ ad images for 5.5" and 12.9" devices.

**Comment by glenn-sorrentino** [comment]
> 

https://keybase.pub/glennsorrentino/onionshare/ios/app%20store/

**Comment by Scripter17** [comment]
Just checking, is this the official OnionShare app store page? https://apps.apple.com/ca/app/onionshare/id1601890129

I couldn't find any mention of it on the [mobile testing page](https://onionshare.org/mobile/) (only the testflight) and this issue makes no mention of it actually being released

**Comment by n8fr8** [comment]
We need to update the website, but yes that is it!
