### ISSUE TITLE
Socket support

### ISSUE THREAD

**Issue by mubashar1199** [onionshare/onionshare-ios#4]
How long it will take for this project release and does it support socket connection as i am planning to create peer to peer chat via tor?

**Comment by tladesignz** [comment]
You don't need this project to get released to take it as an example on how to create your project. This is open source. Just download it and read the source code.

If that doesn't help you, I suggest you go to https://torproject.org/ and read all the documentation you can find there on how to use Tor.

Please stop asking for support for your project in unrelated issue tracker tickets. This is not a Tor support forum.
