### ISSUE TITLE
OnionShare iOS

### ISSUE THREAD

**Issue by sdfinest** [onionshare/onionshare-ios#51]
I am curious how well does the OnionShare application work on iOS? I am asking this question because when I downloaded the Tor browser application for iOS; I had connection issues. The Tor browser application worked 50% of the time. Hopefully, this won’t be the case with the OnionShare application…..

**Comment by tladesignz** [comment]
When you say "Tor Browser application" do you mean this one? https://apps.apple.com/gb/app/tor-browser-ornet-onion-vpn/id1177964608

This is a copycat which makes money off of the back of the Tor Projects and Guardian Projects work. We don't have anything to do with them.


That being said - if you have trouble connecting with that app, you might as well have trouble connecting with OnionShare, depending on the amount of effort censoring Tor in your region.

Why not just try it out?

**Comment by sdfinest** [comment]
Hello, so the iOS Tor browser application you mentioned above; I tried that application in the past and I had connection issues. Unfortunately, iOS does not have a true Tor browser application. **_This why I am curious to know if anyone has had any issues using the OnionShare application on iOS._**

**Comment by tladesignz** [comment]
https://onionbrowser.com is the officially endorsed Tor browser for iOS. Done by yours, humbly. In close contact with the Tor Project.

Just try to use OnionShare and see for yourself. Note: It is not a browser. It creates a Tor service where others can download from.

**Comment by sdfinest** [comment]
All right I will give it a try; I appreciate your input.
