### ISSUE TITLE
Action Priority & Clarity

### ISSUE THREAD

**Issue by glenn-sorrentino** [onionshare/onionshare-ios#8]
**Current**
- Configuring a bridge is the first option in the UI, but is it the most important thing to users? 
- Does the bridge icon communicate what it is? 
- Should the user use the actions in the header or in the body?

**Expected**
- Use an overflow to group secondary and tertiary actions together.
- I'm considering adding photos/files in the header secondary in the contexts of the empty state and after files are initially added. The user has the actions with greater clarity and emphasis in the primary area of the screen, so using an overflow isn't hiding any functionality. After a file is added, those actions become more secondary and don't need to be always-present in the interface.

![actions-priority-clarity](https://user-images.githubusercontent.com/28545431/159768378-8984f1e9-d4fd-4d5e-8f69-1ba9ec472403.png)

**Comment by tladesignz** [comment]
Fixed here:
https://github.com/tladesignz/AdParticipesCumCepis/commit/354bedae8ef39a95d01cad9cbbde8ca57bb5079e
