### ISSUE TITLE
Sheet UI - Sharing State

### ISSUE THREAD

**Issue by glenn-sorrentino** [onionshare/onionshare-ios#9]
**Current**
- Sheet heading needs greater hierarchy
- UI text should have consistent emphasis on key words.
- Share button gets lost in the UI
- The box-shadow is pretty strong. 
- The button should sized consistently with the [primary CTA in the ready-state](https://github.com/onionshare/onionshare-ios/issues/10).
- The styles appear as: 
`sheet { box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.9); }
h1 { font-size: 17pt; }
button { width: fit-content; } `

**Expected**
- Add padding and background color to sharing buttons to add emphasis.
- Full-width button
- Bold the important words in the UI text.
- uniform alignment of UI elements 
- Styles adjusted to:
`sheet { box-shadow: 0px 0px 24px rgba(0, 0, 0, 0.14); } 
h1 { font-size: 22pt; font-weight: bold; }
button { width: 100%; font-weight: normal; }`

![sheet-sharing-state](https://user-images.githubusercontent.com/28545431/159769667-56d56fe8-6761-41e4-99e0-ec13a857277e.png)

**Comment by tladesignz** [comment]
Fixed in https://github.com/tladesignz/AdParticipesCumCepis/commit/5afd171853a8181d1284727e05d877aaf99f34a1
